name = "goose"
version = "2.0.0"
description = "A Gleam WebSocket consumer for AT Protocol Jetstream events"
licences = ["Apache-2.0"]
repository = { type = "github", user = "bigmoves", repo = "goose" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_crypto = ">= 1.5.0 and < 2.0.0"
ezstd = ">= 1.2.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"
logging = ">= 1.3.0 and < 2.0.0"
exception = ">= 2.1.0 and < 3.0.0"
gramps = ">= 6.0.0 and < 7.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
